let mySprite = sprites.create(img`
    ....................
    ....................
    ......fff2fff.......
    ....fff22222fff.....
    ...ffff2f2f2ffff....
    ...ffff22222ffff....
    ..fffffff2fffffff...
    ..fff21ff2ff12fff...
    ..fffffff2fffffff...
    ..fffff22222fffff...
    ..fff1fffffff1fff...
    ..fff21fffff12fff...
    ..ffff21fff12ffff...
    ...ffff21212ffff....
    ...fffffffffffff....
    ....fffffffffff.....
    ......fffffff.......
    .......f...f........
    .......f...f........
    ......fff.fff.......
    `, SpriteKind.Player)
